# -*- coding: utf-8 -*-
"""백준 단계별로 풀어보기 브루트포스

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_qXxRYC31L3tFX-IWwVJyG6PAPvc3NHq
"""

#2798번 블랙잭
n,m = input().split()
n = int(n)
m = int(m)
nums = []
ans = 0

nums = input().split()

for i in range(n) : 
  nums[i] = int(nums[i])

for i in range(n) : 
  for j in range(i+1,n) : 
    for l in range(j+1,n) : 
      if nums[i]+nums[j]+nums[l] <= m and nums[i]+nums[j]+nums[l] > ans : 
        ans = nums[i]+nums[j]+nums[l]

print(ans)

#2231번 분해합
n = int(input())

for i in range(n) : 
  temp = i
  ans = i
  while temp > 0 : 
    ans += temp%10
    temp = temp//10

  if ans == n : 
    break
  
if i == n-1 : 
  print(0)
else : 
  print(i)

#7568번 덩치
n = int(input())
weight = [0]*n
height = [0]*n
rank = [1]*n

for i in range(n) :
  weight[i],height[i] = input().split()
  weight[i] = int(weight[i])
  height[i] = int(height[i])
  rank[i] = 1

for i in range(n) : 
  for j in range(n) : 
    if weight[i] < weight[j] and height[i] < height[j] : 
      rank[i] += 1

for i in range(n) : 
  print(rank[i],end=' ')

#1018번 체스파 다시 칠하기
import sys
n,m = input().split()
n = int(n)
m = int(m)
min = sys.maxsize

wb = [['W','B','W','B','W','B','W','B'],['B','W','B','W','B','W','B','W'],['W','B','W','B','W','B','W','B'],['B','W','B','W','B','W','B','W'],['W','B','W','B','W','B','W','B'],['B','W','B','W','B','W','B','W'],['W','B','W','B','W','B','W','B'],['B','W','B','W','B','W','B','W']]
bw = [['B','W','B','W','B','W','B','W'],['W','B','W','B','W','B','W','B'],['B','W','B','W','B','W','B','W'],['W','B','W','B','W','B','W','B'],['B','W','B','W','B','W','B','W'],['W','B','W','B','W','B','W','B'],['B','W','B','W','B','W','B','W'],['W','B','W','B','W','B','W','B']]

board = [[0]*m for i in range(n)]
temp = [[0]*8 for i in range(8)]

for i in range(n) : 
  board[i] = input() 

for i in range(n-7) : 
  for j in range(m-7) : 
    count_wb = 0
    count_bw = 0
    for x,a in zip(range(i,i+8),range(8)) : 
      for y,b in zip(range(j,j+8),range(8)) : 
        temp[a][b] = board[x][y]
    for c in range(8) : 
      for d in range(8) : 
        if temp[c][d] != wb[c][d] : 
          count_wb += 1
        if temp[c][d] != bw[c][d] : 
          count_bw += 1
    if min > count_wb : 
      min = count_wb
    if min > count_bw : 
      min = count_bw

print(min)

#1436번 영화감독 숌
def is_end_num(num) : 
  num_list = []
  while num : 
    num_list.append(num%10)
    num = num//10
  for i in range(len(num_list)-2) : 
    if num_list[i] == 6 and num_list[i+1] == 6 and num_list[i+2] == 6 :
      return True

n = int(input())
count = 0  
num = 666

while count < n : 
  if is_end_num(num) : 
    count += 1
  num+=1
print(num-1)

1
