# -*- coding: utf-8 -*-
"""코드업 1001~

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eZptbo84leefqHu-7o1d-ze8SxOgtZ_A
"""

#1001
print("Hello")

#1002
print("Hello World")

#1003
print("Hello")
print("World")

#1004
print("\'Hello\'")

#1005
print("\"Hello World\"")

#1006
print("\"!@#$%^&*()\"")

#1007
print("\"C:\Download\hello.cpp\"")

#1008
print("\u250c\u252c\u2510")
print("\u251c\u253c\u2524")
print("\u2514\u2534\u2518")

#1010
n = input()
print(n)

#1011
n = input()
print(n)

#1012
n = float(input())
print("%f"%n)

#1013
a,b = input().split()
print("{} {}".format(a,b))

#1014
a,b = input().split()
print("{} {}".format(b,a))

#1015
n = float(input())
print("%.2f"%n)

#1017
a = input()
print("{} {} {}".format(a,a,a))

#1018
a = input()
h = a.split(':')[0]
m = a.split(':')[1]

print("{}:{}".format(h,m))

#1019
a = input()
y = int(a.split('.')[0])
m = int(a.split('.')[1])
d = int(a.split('.')[2])

print("%04d.%02d.%02d"%(y,m,d))

#1020
a = input()
print("{}{}".format(a.split('-')[0],a.split('-')[1]))

#1021
a = input()
print(a)

#1022
a = input()
print(a)

#1023
f = input()
a = f.split('.')[0]
b = f.split('.')[1]
print(a)
print(b)

#1024
n = input()
m = list(n)
for i in range(len(m)):
  print("\'{}\'".format(m[i]))

#1025
n = input()
m = list(n)
for i in range(len(m)):
  print("[{}]".format(int(m[i])*(10**(4-i))))

#1026
n = input()
m = n.split(':')[1]
print(int(m))

#1027
n = input()
m = n.split(".")
print("%02d-%02d-%04d"%(int(m[2]),int(m[1]),int(m[0])))

#1028
n = input()
print(n)

#1029
n = float(input())
print("%.11lf"%n)

#1030
n = input()
print(n)

#1031
n = int(input())
print("%o"%n)

#1032
n = int(input())
print("%x"%n)

#1033
n = int(input())
print("%X"%n)

#1034
n = input()
m = '0o' + n
m = int(m,8)
print(m)

#1035
n = input()
m = '0x' + n
m = int(m,16)
l = oct(m)
l = str(l)
l=l.replace("0o","")
print(l)

#1036
n = input()
print(ord(n))

#1037
n = input()
print(chr(int(n)))

#1038
a,b = input().split()
c = int(a)+int(b)
print(c)

#1039
a,b = input().split()
c = int(a)+int(b)
print(c)

#1040
n = int(input())
print(-n)

#1041
n = input()
m = ord(n)
m = m+1
print(chr(m))

#1042