# -*- coding: utf-8 -*-
"""백준 단계별로문제풀기 기본수학1,2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvMfgFjYR-CXbDnSwNHlojviN0VYE3km
"""

#10757 큰수 A+B
a,b = input().split()
a = int(a)
b = int(b)

c = a+b
print(c)

#11653번 소인수분해
import math
n = int(input())

def factorization(m) :  
  for i in range(2,m+1):
     if m % i == 0:
       print(i)
       l = m // i
       if l == 1 : break
       factorization(l)
       break

factorization(n)

#1929번 소수구하기
m,n = input().split()
m = int(m)
n = int(n)
arr = [True]*(n+1)
arr[1] = False
def is_prime_num(m,n) : 
  for i in range(2,n) : 
    j = 2
    while i*j <= n : 
      l = i*j
      arr[l] = False
      j += 1
      
is_prime_num(m,n)
for i in range(m,n+1) : 
  if arr[i] : print(i)

#4948번 베르트랑 공준

def is_prime_num(n) :
  for i in range(2,int((2*n)**0.5)+1):
      for j in range(2*i, 2*n+1, i):
          arr[j] = False

n = int(input())
while n != 0 : 
  arr = [False,False] + [True]*(2*n+1)
  is_prime_num(n)
  print(sum(arr[n+1:2*n+1]))
  n = int(input())

#9020번 골드바흐의 추측
n = 10000
primes = []
#def prime(n) :
arr = [False,False] + [True]*(n+1)
for i in range(2,n+1):
  if arr[i]:
   primes.append(i)
  for j in range(2*i, n+1, i):
     arr[j] = False

def goldbach(num) : 
  x = num//2
  for i in range(x,num) : 
    if i in primes and num-i in primes : 
      return num-i,i
  
n = int(input())
for i in range(n) :
  even = int(input())
  a,b = goldbach(even)
  print("{} {}".format(a,b))

#1085번 직사각형에서 탈출
x,y,w,h = input().split()
x = int(x)
y = int(y)
w = int(w)
h = int(h)

print(min(abs(x-w),x,y,abs(y-h)))

#3009번 네 번째 점
x1,y1 = input().split()
x2,y2 = input().split()
x3,y3 = input().split()

x1 = int(x1)
y1 = int(y1)

x2 = int(x2)
y2 = int(y2)

x3 = int(x3)
y3 = int(y3)

x4 = 0
y4 = 0

if x1 == x2  :
  x4 = x3
elif x1 == x3 : 
  x4 = x2
else : x4 = x1

if y1 == y2  :
  y4 = y3
elif y1 == y3 : 
  y4 = y2
else : y4 = y1

print("{} {}".format(x4,y4))

#4153번 직각삼각형

while True : 
  x,y,z = input().split()
  x = int(x)
  y = int(y)
  z = int(z)
  
  if x == 0 and y == 0 and z == 0 : break

  l = sorted([x,y,z])
  if l[0]**2 + l[1]**2 == l[2]**2 : print("right")
  else : print("wrong")

#3053번 택시 기하학
import math
r = float(input())
print("%.6f"%(math.pi*r*r))
print("%.6f"%(2*(r**2)))

#1002번 터렛
n = int(input())

for i in range(n) : 
  x1,y1,r1,x2,y2,r2 = input().split()
  x1 = int(x1)
  y1 = int(y1)
  r1 = int(r1)

  x2 = int(x2)
  y2 = int(y2)
  r2 = int(r2)

  l = ((abs(x1-x2))**2 + (abs(y1-y2))**2)
  r = (r1+r2)**2
  r0 = (r1-r2)**2

  if l == 0 :
    if r1==r2: 
      print(-1) 
    else : 
     print(0)
  else : 
    if l == r or l == r0: 
      print(1)
    elif l > r or l < r0: 
      print(0)
    else : 
      print(2)

