# -*- coding: utf-8 -*-
"""백준 단계별로문제풀기 if문

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNfwSugNUzOwuRWcqRtlCn6LxgUfN3vR
"""

#14681번 사분면고르기
x = int(input())
y = int(input())

if x > 0 and y > 0 : print(1)
elif  x < 0 and y > 0 : print(2)
elif  x < 0 and y < 0 : print(3)
else : print(4)

